name: orangleliu 笔记本
markdown: redcarpet
redcarpet :
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
url : http://orangleliu.info
language: zh-cn
encoding: utf-8
highlighter: pygments
#pygments: true
#lsi: true
