name: 草依山的Javascript世界 
markdown: redcarpet
redcarpet :
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
url : http://jser.me
pygments: true
#lsi: true
